[package]
name = "big_num_math"
version = "0.1.0"
edition = "2021"
authors     = [ "software9119.technology" ]
license     = "MIT"
description = "Simple library for computations on large numbers."
keywords    = [ "math", "large-numbers" ]
categories  = [ "no-std", "mathematics" ]
repository  = "https://github.com/bravequickcleverfibreyarn/big_num_math"
